<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Parser.Plugins.BuiltIn</AssemblyName>
    <RootNamespace>Parser.Plugins.BuiltIn</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Parser.Abstractions\Parser.Abstractions.csproj" />
    <ProjectReference Include="..\Parser.Core\Parser.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>
</Project>
