<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Parser.Storage.Sqlite</AssemblyName>
    <RootNamespace>Parser.Storage.Sqlite</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Parser.Abstractions\Parser.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.7" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>
</Project>
